[package]
name = "lethal-company-mod-installer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
home = "0.5.5"
reqwest = {version = "0.11.22", features = ["blocking"]}
zip-extract = "0.1.2"
